### ISSUE TITLE
Widget timeline

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#144]

**Comment by mguellsegarra** [comment]
@ecarreras 

Estava desenvolupant aquest nou widget, i fent proves amb el webclient, editant una vista de  formulari de `res.partners`, volia afegir les dues noves propietats:

` summaryField="name" titleField="date"`

Per tal de poder indicar al widget quins dos valors del registre hauria de mostrar per a cada item.

El tema és que em sembla que haurem de modificar alguna altra cosa, o fer-ho d'alguna altra manera, ja que al guardar l'XML em dóna un error de validació:

![Screenshot 2022-02-11 at 11 04 15](https://user-images.githubusercontent.com/5711443/153572524-d5c0e4f1-b2d2-4726-8baa-ab8bc3b138a7.png)

**Comment by mguellsegarra** [comment]
Trobo òptim el que dius d'afegir un paràmetre genèric com `widgetProps`, de fet hi havia pensat en alguna cosa similar ;) Així evitem problemes en que s'afegeixin més atributs del compte, i tenim flexibilitat.

Però el que et sigui més còmode i ràpid!

**Comment by mguellsegarra** [comment]
> A mi també m'agrada el `widgetProps` ara tinc una reunió, intento fer-ho el més ràpid possible per no bloquejar. Això ho estàs fent a ovlab? per aplicar-ho allà?

Sí, faig proves a ovlab de develop ;)

**Comment by ecarreras** [comment]
Per fer-ho més compatible amb els atributs que ja hi ha ho poso com a `widget_props`, ja està aplicat a `ovlab`

**Comment by mguellsegarra** [comment]
Hola!

He modificat la vista de `res.partner.form` a `ovlab`, per tal de ajustar el camp `events` de la següent manera:

```
<field colspan="4" name="events" nolabel="1" widget="timeline" widget_props="{'titleField':'date','summaryField':'name'}" />
```

Així, aconsegueixo que el widget de la pestanya "Historial" del detall d'un partner, es mostri de la següent manera:

![new_timeline_widget](https://user-images.githubusercontent.com/5711443/153830374-cca0667f-1c26-421c-8638-8c25f397eabf.gif)

Li pots fer una ullada al mateix entorn de ovlab, he pujat els canvis a `develop`, en breu es farà la build  ;)
