### ISSUE TITLE
Evitar race conditions bloquejant els botons de la barra d'accions quan es carrega un form/tree

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#147]
Quan es carrega una vista de tree o form, la barra d'accions mostra els botons sense bloquejar.

Caldria bloquejar els botons fins que la vista estigui carregada, així s'evitaran possibles race conditions.

**Comment by mguellsegarra** [comment]
@ecarreras 

Ajustat! 

![blocktreebutonsrace](https://user-images.githubusercontent.com/5711443/154041701-155075d3-6d06-4fca-baef-f9a5eeac4e3a.gif)

Vigent a develop de moment :)

**Comment by ecarreras** [comment]
Genial! Per mi ja es pot mergejar a main!
