### ISSUE TITLE
Implementar acció create `0` quan un one2many no tingui id del pare

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#148]
En formularis que provenen d'un assistent  amb camps `one2many` i que no tenen una `id` fins que no guardem, cal que tractem els elements que es creen dins del one2many enviant l'acció `0` + id.

**Comment by mguellsegarra** [comment]
@ecarreras 

Intento reproduïr el bug, però no me'n surto de poder guardar l'assistent, perquè em dóna un error de que el número de compte no és únic:

![Screenshot 2022-02-16 at 10 37 28](https://user-images.githubusercontent.com/5711443/154236973-e279e04e-795d-473c-b077-a05e79d8e65f.png)

Revisant el vídeo a tu no et va saltar l'error, amb el que sospito que alguna cosa no dec fer del tot bé... saps què pot ser?

**Comment by ecarreras** [comment]
Ah crea un altre número de compte o elimina el que ja hi ha.

**Comment by mguellsegarra** [comment]
@ecarreras 

He pujat una primera versió del nou funcionament dels `*2many` a `develop`. Fes-hi una ullada a veure què hi trobes. 

Veuràs que a la barra d'accions dels one2many he eliminat el botó de guardar, ja que amb el funcionament que hem canviat, a imatge de com funciona el GTK, aquest botó em complicava tot el muntatge. Ho comentem a veure si trobem com fer-ho millor.

**Comment by mguellsegarra** [comment]
> L'únic que quan guardar un registre de one2many i es queda el formulari per continuar afegit i vols cancel·lar et diu si vols descartar els canvis (en realitat no n'hi ha de canvis)

Ara ho estava mirant, però no soc capaç de reproduïr-ho a `ovlab`:

![bug](https://user-images.githubusercontent.com/5711443/154642995-4e0e3b4c-9c11-449e-b956-66e0c71a78c4.gif)

En quin entorn feies aquestes proves? És estrany!

**Comment by ecarreras** [comment]
Diria que no està aplicat a ovlab, ho vaig fer en un local meu. Haig de mirar que ovlab no s'estan construint els builds.

**Comment by mguellsegarra** [comment]
@ecarreras t'ha passat més aquest error? Ho he tornat a provar en local i a `ovlab`, i no puc reproduïr-ho :/

**Comment by mguellsegarra** [comment]
Corregit!
