### ISSUE TITLE
Dashboards: Guardar posició i mides

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#170]

**Comment by mguellsegarra** [comment]
@ecarreras 

Estava implementant aquest tema per tal de guardar les posicions de cada un dels widgets d'un dashboard.

Amb la info que rebo amb l'XML, tinc la posició i l'acció.

Per actualitzar cada un dels items, entenc que hauria de fer un update/write de `board.board.line` amb l'id corresponent de cada item.

Això ho puc obtenir llegint l'objecte `board.board` amb l'id que tinc al context (`active_id`). El `one2many` de `line_ids` té els objectes dels items.

Serien dues crides addicionals, una per llegir el `board.board` i l'altre per llegir els items de `board.board.line`.

Crec que aquestes dues crides ens les podriem estalviar si a l'hora de construïr la vista des del backend, s'hi insertés la `id` del `board.board.line` en cada un dels items:

https://github.com/gisce/erp/blob/ab54add6056729e709c1eaab3f6c9d1f0060cb7e/addons/official/board/board.py#L18

Com ho veus?

**Comment by ecarreras** [comment]
@mguellsegarra genial, jo també hi desplegaré l'eliminació del `fields_view_get`, ara ho provaré :D

**Comment by ecarreras** [comment]
Funciona perfectament!
