### ISSUE TITLE
Dashboards: GraphIndicator amb evaluació de colors

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#171]

**Comment by mguellsegarra** [comment]
@ecarreras Acabo de pujar a `develop` els canvis per a que s'evaluin les condicions de color en un GraphIndicator:

![Screenshot 2022-03-08 at 17 52 41](https://user-images.githubusercontent.com/5711443/157286246-4bd1fcd8-4f43-43f5-92a4-e1a22ec86d36.png)

Fes-hi una ullada i em dius com ho veus ;)

**Comment by ecarreras** [comment]
m'espero el build i ho provo 👏🏻

**Comment by ecarreras** [comment]
Genial!
![image](https://user-images.githubusercontent.com/294235/157290334-074d49c6-8150-435e-90f0-e2889b130c32.png)
