### ISSUE TITLE
Dashboards: GraphIndicator amb 2 domains

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#173]
El primer domain podem fer servir el que vé marcat per l'acció, i a nivell de vista, podem afegir una nova propietat a la vista:

```
<graph type="indicator" totalDomain="[('open', '=', True)]" />
```

Com ho veuries @ecarreras ? Caldria ajustar el `.rng` per permetre el paràmetre `totalDomain` ?

En cas que no arribi el `totalDomain`, es mostraria un indicador amb una xifra només.

**Comment by mguellsegarra** [comment]
@ecarreras 

Primera versió de l'indicador, a veure com ho veus:

![Screenshot 2022-03-09 at 13 21 04](https://user-images.githubusercontent.com/5711443/157440963-59054ee0-6331-4489-837b-b46dcee6847b.png)

No sé si posar `total: `, una barra de denominador `10 / 70` o com seria millor...

**Comment by ecarreras** [comment]
@mguellsegarra ara modifico el `.rng` i crec que seria millor fer un `X / Y`

**Comment by ecarreras** [comment]
@mguellsegarra estava pensant que potser seria interessant també mostrar un percentatge en gros i abaix  en petit el numero / total si li diem un atribut tipus `showPercent="1"`

Després a les regles d'atributs podríem passar el valors: `value` que és el count i el `percent` que és el percentatge calculat, per si volem fer regles en base el percentatge.

**Comment by mguellsegarra** [comment]
@ecarreras Em sembla bona idea! Ara m'hi poso a implementar-ho. Si toques el `rng` per afegir el `showPercent`, ja modifico també el `ooui`.

**Comment by mguellsegarra** [comment]
Què et sembla @ecarreras ?

![Screenshot 2022-03-09 at 14 48 07](https://user-images.githubusercontent.com/5711443/157454403-8eb3d7b4-b97e-4bcd-b519-74b0e16a8c13.png)

Pel tema del color del percentatge, pot ser que tal com està montat ara el mètode del `parse_condition`, hauriem de fer dues crides per separat, una pel color del value i l'altre pel percentatge, i obtenir també la condició del color del percent per separat?

**Comment by ecarreras** [comment]
Jo crec que el color ha d'aplicar a tot el widget, però que en el paràmetre de valors passar-hi `{'value': value, 'percent': percent}` i així el que escriu la condició ho pot escriure fent servir el valor o el percentatge

**Comment by mguellsegarra** [comment]
Perfecte, quedaria algo com això:

![Screenshot 2022-03-09 at 15 06 28](https://user-images.githubusercontent.com/5711443/157457681-ef15e7c2-afa5-4517-95e9-e1608eb44478.png)

Si et sembla bé, ho pujo a `develop` perquè ho puguis provar.

@ecarreras

**Comment by ecarreras** [comment]
@mguellsegarra genial!

**Comment by mguellsegarra** [comment]
Fes-hi una ullada, en breu es farà la build a `develop` amb els canvis aplicats ;)
