### ISSUE TITLE
Dashboards: Afegir botó per a refrescar

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#174]
He afegit un botó de refresh als dashbaords, per a que em recarregui tot el dashboard, estava cansat d’obrir cada cop una pestanya nova per fer proves.

Més endavant també s’hi pot afegir un altre botó de refrescar el contingut amb un timer periòdic de refresh:

![refresh-dashboards](https://user-images.githubusercontent.com/5711443/157483656-e4e57bde-6807-4198-ab7c-fbf9ae9488de.gif)

@ecarreras Si et sembla bé, ho pujo a develop ;)

**Comment by ecarreras** [comment]
Perfecte!
