### ISSUE TITLE
Dashboards: Afegir botó a les cards per obrir acció com a nou tab

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#175]

**Comment by mguellsegarra** [comment]
Acabo d'implementar-ho, tal com vam comentar apareixerà el botó a la card per a obrir el tree en funció si l'acció del dashboard item té una vista tree associada.

Si li vols donar un cop d'ull @ecarreras , estarà disponible a `develop` en breu ;)

**Comment by ecarreras** [comment]
Genial @mguellsegarra ! queda genial, podries canviar l'icona a `<ExportOutlined />` pq el de maximizar potser el farem servir més endavant

**Comment by mguellsegarra** [comment]
Canviat! :D 

En breu vigent a develop

**Comment by ecarreras** [comment]
Genial!
