### ISSUE TITLE
Glitch visual al canviar de tab

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#176]
Al canviar entre tabs, hi ha un comportament estrany que fa redimensionar l'action bar:

![glitch_change_Tab](https://user-images.githubusercontent.com/5711443/158176760-cc5360e2-c7d8-4cb1-9fa9-86f104464660.gif)

Debugant he vist que ho provoca el component `<Affix>` que vam introduïr perquè la barra d'accions quedés sticky al fer scroll. 

El culpable és l'offset que vaig afegir-hi per a que no es solapés amb la barra superior. Sense aquest offset, el glitch no succeeix.

Ho apunto aquí perquè crec que potser interessa més donar prioritat a la resta de features, o si creus que és crític ho miro, @ecarreras

**Comment by ecarreras** [comment]
No, jo crec que de moment no es crític

**Comment by mguellsegarra** [comment]
He eliminat aquest glitch. He substituït el component d'`Ant` per aquest estil CSS, que sembla que sigui més eficient i no ha de recalcular les posicions:

```
    <div style={{ position: "sticky", top: 80, zIndex: 99 }}>
            {...}
    </div>
```

ara quan es canvia de tabs ja no apareix el glitch, i continuem mantenint el tema de que la barra es quedi fixada a dalt ;)

En breu disponible a `develop`.

@ecarreras

**Comment by ecarreras** [comment]
Oh! genial 💪🏻
