### ISSUE TITLE
Dashboards: Mostrar tree senzill

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#177]

**Comment by mguellsegarra** [comment]
@ecarreras 

Ja tinc implementat el tree senzill dins d'un item del dashboard:

![tree](https://user-images.githubusercontent.com/5711443/158376595-5714a8a9-62b2-458f-b896-970242ba32d2.gif)

He afegit les barres d'scroll i implementat que quan es faci doble click en una fila es carregui el form amb aquell registre en una nova pestanya.

Ho he pujat a `develop` perquè puguis fer-hi una ullada ;)

**Comment by ecarreras** [comment]
Genial! funciona perfectament 💪🏻
