### ISSUE TITLE
Dashboards: Mostrar botó engranatge per editar dashboard

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#179]

**Comment by mguellsegarra** [comment]
@ecarreras 

He afegit un nou botó a la barra d'accions de les vistes de dashboard per a poder accedir directament a la configuració del dashboard en una nova pestanya:

![config_dashboard](https://user-images.githubusercontent.com/5711443/158547951-1b9b5c75-2aa2-4fc6-ba4a-7f45a36b0f0a.gif)

Ja em diràs, ho teniu disponible a `develop` en breu ;)

**Comment by ecarreras** [comment]
Genial!
