### ISSUE TITLE
Dashboard: gràfiques lineals, de barres i pie

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#181]
Relacionada https://github.com/gisce/webclient/issues/16

**Comment by mguellsegarra** [comment]
@ecarreras 

He pujat una primera versió dels gràfics de línies amb "count" a `ovlab` - `develop`. Fes-hi una ullada ;)

**Comment by ecarreras** [comment]
@mguellsegarra per soportar més d'un indicador a les y si vols ho fem en dos passos:
1. Suportar més d'un valor mostrant un altre valor indepenent (i llegenda)
2. Fent stacked

**Comment by ecarreras** [comment]
@mguellsegarra He vist una cosa, que harem de adaptar: Quan fem servir els many2one per fer-los servir com valor, p.ex el següent cas:

![image](https://user-images.githubusercontent.com/294235/161034314-49e7181b-03ea-4dc5-8001-bcfafb7f7e96.png)

- Hem d'agrupar per ID, però al label hauriem de mostrar el nom
- També hem de revisar si estem passant el context al fer el read, ja que no sembla que estigui agafant les tarifes traduïdes.

**Comment by mguellsegarra** [comment]
@ecarreras 

Miro el tema dels Many2one amb el tractament de ids-nom.

Estava revisant el tema del context, però veig que sí que li enviem... potser ens fa ballar el cap el tema que el nom de les accions no l'estem traduïnt i el posem en català, i la resta de UI està en castellà:

![Screenshot 2022-04-01 at 09 20 36](https://user-images.githubusercontent.com/5711443/161215112-b60fd61c-6729-41ce-b07a-8003fda727c2.png)

**Comment by ecarreras** [comment]
@mguellsegarra
- ok, vaig a revisar les traduccions a veure que siguin correctes.
- Pel tema dels Many2one estic pensant que també haurem de fer una cosa similar als selection, i hauriem d'agafar el valor del label del selection per fer el label, i el valor del selection per agrupar.

**Comment by mguellsegarra** [comment]
@ecarreras 

> Pel tema dels Many2one estic pensant que també haurem de fer una cosa similar als selection, i hauriem d'agafar el valor del label del selection per fer el label, i el valor del selection per agrupar.

OK, cap problema. Els One2many cal fer-hi alguna cosa especial, o potser no té sentit fer-los servir per fer-hi gràfiques?

**Comment by ecarreras** [comment]
> OK, cap problema. Els One2many cal fer-hi alguna cosa especial, o potser no té sentit fer-los servir per fer-hi gràfiques?

@mguellsegarra jo crec que no té sentit els one2many

pel tema de les traducciones, efectivament estaven malament les traduccions 😝

**Comment by mguellsegarra** [comment]
@ecarreras  Fet!

He creat un nou item al dashboard per a que faci un pie segons l'estat de la polissa, per provar el tema dels selections. El de llista de preus també apareix correctament crec:

![Screenshot 2022-04-01 at 10 24 10](https://user-images.githubusercontent.com/5711443/161225226-f102e114-9bdf-4279-8b09-5b601a95bc8f.png)

En breu disponible a `develop` - `ovlab` perquè ho puguis provar ;)

**Comment by ecarreras** [comment]
Ohhh! té super bona pinta!!!!! ❤️ ho provo una mica i per mi ja podem posar a main aquesta part, que la gent de la ofi ja té ganes de fer més gràfiques al nostre dashboard!

**Comment by ecarreras** [comment]
@mguellsegarra gas a això! ja pot anar a main 🚀

**Comment by mguellsegarra** [comment]
@ecarreras Mergejat a `main`, en breu es construiran les builds :D
