### ISSUE TITLE
Icons and suffixes in GraphIndicators

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#183]
@ecarreras 

He afegit el tractament de icones i suffixes al component GraphIndicator:

![Screenshot 2022-03-24 at 10 49 11](https://user-images.githubusercontent.com/5711443/159889488-b8d1104b-0771-4a02-99fb-0d5232028844.png)

Està vigent a `develop`.

**Comment by mguellsegarra** [comment]
Queda pendent que toquem el `.rng` per permetre l'atribut `suffix`:

![Screenshot 2022-03-24 at 10 46 55](https://user-images.githubusercontent.com/5711443/159889361-fb529163-6f18-43af-8d76-337c19c385ea.png)

**Comment by mguellsegarra** [comment]
Per provar-ho a `ovlab` i abans de passar-ho a main, crec que ens bloqueja aquesta issue: https://github.com/gisce/webclient/issues/197

**Comment by ecarreras** [comment]
@mguellsegarra pot ser que pel `percent` no funcioni els icons?

**Comment by ecarreras** [comment]
> Queda pendent que toquem el `.rng` per permetre l'atribut `suffix`

Fet!

**Comment by mguellsegarra** [comment]
> @mguellsegarra pot ser que pel percent no funcioni els icons?

He afegit el valor `percent` a l'hora d'evaluar l'icon.

Vigent a `ovlab` - `develop`.

He creat aquesta PR: https://github.com/gisce/webclient/pull/198

**Comment by ecarreras** [comment]
Funciona perfectament! Pot anar a main! 🚀
