### ISSUE TITLE
Gràfiques amb eixos stacked

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#185]
- Tenir en compte: https://github.com/gisce/react-ooui/issues/181#issuecomment-1084377052
- Part de https://github.com/gisce/webclient/issues/16

**Comment by ecarreras** [comment]
@mguellsegarra Abans dels stacked, quan es faci més d'una mètrica per eix "x" pensar que la mètrica pugui ser agrupada per un altre field, poso un exemple perquè s'entegui una mica més.

Tenim la taula de lectures, on cada item és una lectura i tenen, un camp de data i un camp de consum, però també tenen un camp periode que és amb el qual volem agrupar i pintar les diferents mètriques, podria ser alguna cosa així:

## Exemple on el label el defineix un camp de la taula
```xml
<graph type="bar>
  <field name="name" axis="x" />
  <field name="consum" operator="+" label="periode" axis="y"/>
</graph>
```
En aquest cas s'hauria de llegir els camps `name`, `consum` i `periode` i agrupar per periode (que és cada color diferent) i despŕes a l'eix de les "x" pel name

## Exemple on pintem dos valors diferents de la taula com a dos mètriques diferents

```xml
<graph type="bar>
  <field name="name" axis="x" />
  <field name="consum" operator="+" axis="y"/>
  <field name="ajust" operator="+" axis="y" />
</graph>
```

**Comment by mguellsegarra** [comment]
Perfecte! Li faig una ullada

**Comment by mguellsegarra** [comment]
@ecarreras 

Pot ser que s'hagi de modificar el `rng` per permetre la propietat label?

Intento insertar l'XML de la vista:

```
<?xml version="1.0"?>
<graph type="bar">
  <field name="name" axis="x"/>
  <field name="consum" label="periode" operator="+" axis="y"/>
</graph>
```

I em dóna l'error:

``` 
"warning -- ValidateError\n\nError occurred while validating the field(s) Código vista: ¡XML inválido para la definición de la vista!"
```

**Comment by ecarreras** [comment]
Voi!

**Comment by ecarreras** [comment]
@mguellsegarra modificat!

**Comment by ecarreras** [comment]
Si si, aquesta és la idea que volia, l'únic que volia començar per les que no fossin stacked, és a dir començar amb 
![image](https://user-images.githubusercontent.com/294235/161776700-6ffaa974-c771-4e7f-b332-e6ed522593ad.png) i després pensar una sintaxis per fer-les stacked.

**Comment by mguellsegarra** [comment]
@ecarreras  Cap problema! He hagut de canviar un parell de paràmetres, però ara ja m'ho mostra com dius: 

![Screenshot 2022-04-05 at 16 34 07](https://user-images.githubusercontent.com/5711443/161778050-19908ea5-bb52-4b17-a9f0-306a4500e572.png)

En breu vigent a develop, i a `ovlab` hi ha una gràfica per a que ho vegis ;)

**Comment by ecarreras** [comment]
De fet a mi m'agrada més staked però la idea és que poguem fer stacked amb una cadena, tipus

`stacked="string"` i que faci stack un stack per cada string.

**Comment by mguellsegarra** [comment]
@ecarreras 

Acabo de pujar tots els canvis que hem anat mirant i ajustant amb el `react-ooui-graphs-playground` al webclient de develop.

Si vols fer-hi una ullada, ja es podria passar a main :)

**Comment by ecarreras** [comment]
Fot-li a main! 💪🏻

**Comment by mguellsegarra** [comment]
Traspassat 💪 💪
