### ISSUE TITLE
Mode edició dashboard per moure widgets

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#186]
Part de https://github.com/gisce/webclient/issues/160

**Comment by ecarreras** [comment]
> L'altre cosa que potser dubto, és que si el mode està desactivat, potser hauriem de bloquejar que es poguessin moure els items. Ara es permet que es moguin, però no es guarden al servidor, i no sé si pot confondre al usuari.

Jo crec que està bé que es puguin moure, potser posarem algun avís de que no es guardaran al servidor si no s'entra en el mode edició. Però de moment ho podem deixar així

Cap a main que va! 🚀

**Comment by mguellsegarra** [comment]
Perfecte, ho pujo junt amb la issue https://github.com/gisce/react-ooui/issues/185 quan ho tinguem lligat
