### ISSUE TITLE
Indicadors en el dashboard amb icona no es mostren correctament

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#187]
![Screenshot 2022-04-04 at 09 58 07](https://user-images.githubusercontent.com/5711443/161500221-e7a1f6dd-2f58-4b97-924b-d13f9f12b508.png)

**Comment by ecarreras** [comment]
Jo ho veig perfecte! 👌🏻 

@mguellsegarra podem aprofitar aquesta branca per millorar l'icona dels que mostren el percentatge que ocupi les dues files? sino es veu molt petit

![image](https://user-images.githubusercontent.com/294235/161503861-51b82c22-7794-46ed-87a8-fb590a49b77a.png)

**Comment by mguellsegarra** [comment]
I tant, ara ho ajusto ;)

**Comment by mguellsegarra** [comment]
@ecarreras A veure com ho veus:

![Screenshot 2022-04-04 at 11 08 00](https://user-images.githubusercontent.com/5711443/161511705-bb23c8eb-ed75-41d3-a1d1-a2f75c4c2153.png)

Vigent a `develop` - `ovlab`, en breu.

**Comment by mguellsegarra** [comment]
Ho passo a `main`, qualsevol cosa ho comentem ;)

**Comment by ecarreras** [comment]
Perfecte!
