### ISSUE TITLE
Ajustar tamany GraphIndicators quan son números alts

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#190]
En casos com aquest, es veuen extramadament petits:

![Screenshot 2022-04-07 at 17 32 19](https://user-images.githubusercontent.com/5711443/162379363-c4586b2d-3e64-481a-82fa-e8a25b0890ee.png)

**Comment by mguellsegarra** [comment]
@ecarreras 

He fet alguns ajustos i crec que ara ja es veu bastant més decent:

![Screenshot 2022-04-08 at 09 06 55](https://user-images.githubusercontent.com/5711443/162382722-29d2d931-cd6c-480f-afc1-d3b3eb462fc7.png)
![Screenshot 2022-04-08 at 09 06 50](https://user-images.githubusercontent.com/5711443/162382727-ea6d4533-5ba6-42e8-9cab-701885fa867f.png)
![Screenshot 2022-04-08 at 09 06 47](https://user-images.githubusercontent.com/5711443/162382729-793ff03e-e06e-4323-8891-8c4abb57f8c6.png)
![Screenshot 2022-04-08 at 09 06 40](https://user-images.githubusercontent.com/5711443/162382731-fa6bce4d-d276-449f-9c03-160f1c6788b8.png)

Ho pujo a `develop` - `ovlab`, i si et sembla també ho passo a `main`, no sé en quin entorn tenies l'indcador.

**Comment by ecarreras** [comment]
Perfecte @mguellsegarra endavant! 🚀 si ho tinc en un entorn `main`

**Comment by mguellsegarra** [comment]
Traspassat a `main` ;)
