### ISSUE TITLE
Widget de fitxer surt tallat

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#192]
![Screenshot 2022-04-26 at 09 03 58](https://user-images.githubusercontent.com/5711443/165241948-4b5cbacd-1d53-4f9d-a82e-e1af6b0fff40.png)

**Comment by mguellsegarra** [comment]
Ho he ajustat per a que aparegui en dues línies:

![Screenshot 2022-04-26 at 12 14 20](https://user-images.githubusercontent.com/5711443/165278024-a59c64eb-df58-470d-97a2-4e799e41ca54.png)

Ho he pujat a `develop` - `ovlab`.

@ecarreras Si et sembla bé, hi ha aquesta [PR](https://github.com/gisce/webclient/pull/227) preparada per a que s'apliqui un cop aprovada ;)

**Comment by ecarreras** [comment]
Perfecte!
