### ISSUE TITLE
Builds i publish a npm de react-ooui mitjançant GH Actions

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/react-ooui#205]
A arrel dels problemes amb les builds que vam tenir el passat divendres, @ecarreras , he estat mirant el tema de que es poguessin fer les builds + publish a npm de `react-ooui`, cada vegada que es faci un push a master.

He estat provant a veure si fallava en una vm Ubuntu 20.04, i m'ha funcionat correctament amb node 16.13.1.

Després he mirat també amb una GH Action, a veure si aconseguia fer el `npm ci` i el build, i també m'ha funcionat bé:

https://github.com/gisce/react-ooui/runs/7495945962?check_suite_focus=true

Si et sembla, podriem pensar en com enfoquem el tema del versionat + publicació a `npm`. Fins ara el versionat el portava manualment amb `npm version`. També podem optar per tirar de històries com el `semantic-release`: https://blog.logrocket.com/complete-workflow-guide-to-publish-a-react-library-to-npm-using-github-actions/

Necessitaria accés a les settings de `react-ooui` per configurar els secrets de les actions, si tens una estona i ho veus bé.

**Comment by ecarreras** [comment]
@mguellsegarra permiso concedido :🧞‍♂️

**Comment by mguellsegarra** [comment]
Pel tema del versionat farem servir: 

A develop: `npm version prelease --preid rc`

**Comment by mguellsegarra** [comment]
Workflow per treballar amb `react-ooui` i les GH Actions:

### FEATURE - Hem fet una nova funcionalitat:

Desenvoluparem en una nova branch de **`feature/xxx`** des de **`master`**.

Al acabar la feature, hem d'assegurar-nos de que la versió del `package.json` és la mateixa que hi ha vigent a `master`, caldrà que des d'aquesta branch de `feature/xxx` fem un `npm version minor`. Això ens pujarà la versió minor, per exemple, si estavem a 0.18.0, ens ho passarà a 0.19.0.

**Per passar-ho a develop:**
- Farem merge de la branch `feature/xxx` a `develop`
- Des de develop, caldrà que fem un `npm version prerelease --preid rc`. Això ens afegirà el `-rc.0`, `-rc.1`,... a la versió.
- Al fer push a `develop`, es dispararà una GH action que el que farà serà fer la build i publicar a `npm`.

**Per passar-ho a master:**
- Farem una PR de la branch `feature/xxx`.
- Al aprovar-se, es dispararà una GH action que el que farà serà fer la build i publicar a `npm`.

### HOTFIX - Hem trobat un bug i hem de pujar un fix:

Desenvoluparem en una nova branch de `hotfix/xxx` des de `master`.

Al acabar el fix, i assegurar-se de que la versió del `package.json` és la mateixa que hi ha vigent a `master`, caldrà que des d'aquesta branch de `hotfix/xxx` fem un `npm version patch`. Això ens pujarà la versió patch, per exemple, si estavem a 0.18.0, ens ho passarà a 0.18.1.

**Per passar-ho a develop:**
- Farem merge de la branch `hotfix/xxx` a `develop`
- Des de develop, caldrà que fem un `npm version prerelease --preid rc`. Això ens afegirà el `-rc.0`, `-rc.1`,... a la versió.
- Al fer push a `develop`, es dispararà una GH action que el que farà serà fer la build i publicar a `npm`.

**Per passar-ho a master:**
- Farem una PR de la branch `hotfix/xxx`.
- Al aprovar-se, es dispararà una GH action que el que farà serà fer la build i publicar a `npm`.

**Comment by ecarreras** [comment]
Diria que hi ha una opció al GitHub per obligar tenir la branca actualizada de "main" així segur que hi ha la última versió sempre

**Comment by mguellsegarra** [comment]
Ho miro! :D

**Comment by mguellsegarra** [comment]
No me'n acabo d'ensortir...

En principi he vist que això ens podria servir:

![Screenshot 2022-08-12 at 09 48 40](https://user-images.githubusercontent.com/5711443/184309339-2abad9e6-dea8-4606-9208-5416c8ad2ad6.png)

Però no aconsegueixo que em funcioni.

A veure si tenim una estona un dia i ho mirem.
