### ISSUE TITLE
Unificar estils d'icones

### ISSUE THREAD

**Issue by ecarreras** [gisce/react-ooui#272]
Hem trobat que al menú els icones d'ant tenen un estil diferent als altres icones:

![image](https://user-images.githubusercontent.com/294235/228809550-cc1e2d64-5f93-46aa-892f-cba33341cd56.png)

Hem vist que es tracte d'aquest estil:

![image](https://user-images.githubusercontent.com/294235/228809634-f31ed5c3-16de-4597-a746-bc913984c728.png)

**Comment by mguellsegarra** [comment]
Ho reviso!

**Comment by mguellsegarra** [comment]
## Before

![before](https://user-images.githubusercontent.com/5711443/229070189-3923685c-b0d8-4ec6-bcaf-76f59afdd10d.png)

## After

![Screenshot 2023-03-31 at 10 37 36](https://user-images.githubusercontent.com/5711443/229070201-d844a44c-c8bc-4a9d-9099-25962a9447f8.png)

**Comment by mguellsegarra** [comment]
@ecarreras Arreglat! Està disponible tant a `ovlab` com a `develop`. Si voleu donar-hi una ullada i validar-ho, després un cop ho trobeu OK es pot aprovar aquesta [PR](https://github.com/gisce/webclient/pull/431) per passar-ho a `main` ;)
