### ISSUE TITLE
Posibilitat de afegir un prefix al valor del label

### ISSUE THREAD

**Issue by opachou** [gisce/react-ooui#448]
Estava fent un gràfic agrupat per categoria de grup i el valor es un nombre i crea aquest range picker
![imagen](https://github.com/gisce/react-ooui/assets/37912888/2b2cab40-f018-481d-be3d-3a7fd42c3ffe)

Estaria bé que es creés la gràfica com aquesta:
![imagen](https://github.com/gisce/react-ooui/assets/37912888/3876c6e1-5896-4fe8-b5d1-e6c20405ea8b)

Perquè així pots deshabilitar el grup 4 sense haver de deshabilitar x per amunt o avall.

He pensat que s'hi, hi hagués un atribut que et deixés posar un prefix al davant del label se solucionaria, ja que l'interpretaria com a string i no ints, o alguna altra solució?

**Comment by ecarreras** [comment]
Fes que el camp sigui un selection I ja està
